name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest }
          - { os: macos-latest }
          - { os: windows-latest }
          - { os: windows-latest, mingw_sys: mingw64, mingw_env: x86_64 }
          - { os: windows-latest, mingw_sys: ucrt64, mingw_env: ucrt-x86_64 }

    steps:
    - uses: actions/checkout@v4

    - name: Configure MSYS2
      if: ${{ matrix.mingw_sys }}
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.mingw_sys }}
        update: false
        install: >-
          mingw-w64-${{ matrix.mingw_env }}-toolchain
          mingw-w64-${{ matrix.mingw_env }}-cmake
          mingw-w64-${{ matrix.mingw_env }}-ninja

    - name: Add MinGW binaries to PATH
      if: ${{ matrix.mingw_sys }}
      run: echo "/mingw64/bin" >> "$GITHUB_PATH"

    - name: Configure CMake (osx cross)
      if: ${{ matrix.os == 'macos-latest' }}
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"

    - name: Configure CMake (MinGW)
      if: ${{ matrix.mingw_sys }}
      shell: msys2 {0}
      run: cmake -B build -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Configure CMake
      if: ${{ matrix.os != 'macos-latest' && !matrix.mingw_sys }}
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Print config.h
      run: cat ${{github.workspace}}/build/config.h

    - name: Build
      if: ${{ !matrix.mingw_sys }}
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Build (MinGW)
      if: ${{ matrix.mingw_sys }}
      shell: msys2 {0}
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Test
      if: ${{ !matrix.mingw_sys }}
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure -C ${{env.BUILD_TYPE}}

    - name: Test (MinGW)
      if: ${{ matrix.mingw_sys }}
      shell: msys2 {0}
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure -C ${{env.BUILD_TYPE}}
